StudentTracking.WebHost/Controllers/ServicesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using StudtentTracking.Data.Entities;
using StudentTracking.Data.Contracts.Repository;
using StudentTracking.WebHost.Helper;

namespace StudentTracking.WebHost.Controllers
{
    [Authorize]
    public class ServicesController : Controller
    {
        private readonly IServiceRepository _serviceRepository;
        private readonly ISchoolRepository _schoolRepository;

        public ServicesController(IServiceRepository serviceRepository,ISchoolRepository schoolRepository)
        {
            _serviceRepository = serviceRepository;
            _schoolRepository = schoolRepository;
        }

        // GET: Services
        public ActionResult Index()
        {
            ViewBag.school = _schoolRepository.GetAll();/*GetAllByUserId(UserInfoHelper.GetUserId());*/
            return View(_serviceRepository.GetAllByUserId(UserInfoHelper.GetUserId()).ToList());
        }


        // GET: Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = _serviceRepository.Get(id);
            if (service == null)
            {
                return HttpNotFound();
            }

            if (service.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.school = _schoolRepository.Get(service.schoolId).schoolName;
            return View(service);
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            ViewBag.SchoolsSelectList = SelectListItemHelper.SchoolsKeyValues();
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "serviceName,schoolId,createdAt,deletedAt,deleted")] Service service)
        {
            if (!ModelState.IsValid)
            {
                return View(service);
            }
            try
            {
                service.userId = UserInfoHelper.GetUserId();
                service.deleted = false;
                service.deletedAt = new System.DateTime(1900, 1, 1);
                service.createdAt = System.DateTime.Now;
                _serviceRepository.Insert(service);
            }
            catch (System.Exception ex)
            {
                TempData["error"] = "Kayıt Ekleme İşlemi Başarısız. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }
            return RedirectToAction("Index");

        }

        // GET: Services/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = _serviceRepository.Get(id);
            if (service == null)
            {
                return HttpNotFound();
            }

            if (service.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                var schools = SelectListItemHelper.SchoolsKeyValues();
                schools.First(i => i.Value == service.schoolId.ToString()).Selected = true;
                ViewBag.SchoolsSelectList = schools;
                return View(service);
        
            
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,serviceName,schoolId,deleted,createdAt,deletedAt")] Service service)
        {
            if (!ModelState.IsValid)
            {
                return View(service);
            }

            var serviceTemp = _serviceRepository.Get(service.Id);

            if (serviceTemp.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            try
            {
                service.userId = UserInfoHelper.GetUserId();
                _serviceRepository.Update(service);
                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                TempData["error"] = "Düzenleme İşlemi Başarısız. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }
            
        }

        // GET: Services/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = _serviceRepository.Get(id);
            if (service == null)
            {
                return HttpNotFound();
            }

            if (service.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.school = _schoolRepository.Get(service.schoolId).schoolName;
            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Service service = _serviceRepository.Get(id);

            if (service.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            try
            {
                _serviceRepository.Delete(service);
                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                TempData["error"] = "Silme İşlemi Başarısız. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }
            
        }

       
    }
}

StudentTracking.WebHost/Views/Services/Create.cshtml
@model StudtentTracking.Data.Entities.Service

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Yeni Kayıt Oluştur</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="form-horizontal col-md-6 col-sm-12">

                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()
                  @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.serviceName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.serviceName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.serviceName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.schoolId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.schoolId, new SelectList(ViewBag.SchoolsSelectList, "Value","Text"), "Okul Seçiniz", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.schoolId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-4 col-md-6">
                            <input type="submit" value="Oluştur" class="btn btn-success" />
                            <a href="@Url.Action("Index","Services")" class="btn btn-default">Listeye Geri Dön</a>
                        </div>
                    </div>

                }



            </div>
        </div>

    </div>
</section>
@section Styles{


}

@section Scripts{


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

StudentTracking.WebHost/Views/Services/Delete.cshtml
@model StudtentTracking.Data.Entities.Service

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var schoolName = ViewBag.school;
}



<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">

        <div class="box-body table-responsive">


            <h3>Silmek İstediğine Emin Misin?</h3>
            <div>

                <dl class="dl-horizontal">                  

                    <dt>
                        @Html.DisplayNameFor(model => model.serviceName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.serviceName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.schoolId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model =>schoolName)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Sil" class="btn btn-default" /> |
                        <a href="@Url.Action("Index","Services")" class="btn btn-primary">Listeye Geri Dön</a>
                    </div>
                }
            </div>

        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

StudentTracking.WebHost/Views/Services/Details.cshtml
@model StudtentTracking.Data.Entities.Service

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var schoolName = ViewBag.school;
}

<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Servis Detayı</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="box-body">
            <div>

                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.serviceName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.serviceName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.schoolId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => schoolName)
                    </dd> 
                    
                </dl>
            </div>

            <div class="col-md-offset-1 col-md-6">
                <a href="@Url.Action("Edit","Services", new { id = Model.Id })" class="btn btn-primary">Düzenle</a>
                <a href="@Url.Action("Index","Services")" class="btn btn-primary">Listeye Geri Dön</a>

            </div>

        </div>
    </div>
</section>

StudentTracking.WebHost/Views/Services/Edit.cshtml
@model StudtentTracking.Data.Entities.Service

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}




<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Düzenle</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="box-body">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.serviceName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.serviceName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.serviceName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.schoolId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.schoolId, new SelectList(ViewBag.SchoolsSelectList, "Value", "Text", Model.schoolId), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.schoolId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @Html.HiddenFor(model=>model.deleted)
                    @Html.HiddenFor(model=>model.createdAt)
                    @Html.HiddenFor(model=>model.deletedAt)

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Kaydet" class="btn btn-default" />
                            <a href="@Url.Action("Index","Services")" class="btn btn-primary">Listeye Dön</a>
                        </div>
                    </div>
                </div>
            }

        </div>
        <!-- /.box-body -->

    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

@section Scripts{

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

StudentTracking.WebHost/Views/Services/Index.cshtml
@model IEnumerable<StudtentTracking.Data.Entities.Service>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var school = (IEnumerable<StudtentTracking.Data.Entities.School>)ViewBag.school;
}


<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Servisler</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="box-body table-responsive">
        
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.serviceName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.schoolId)
                    </th>
                    <th>İşlem</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.serviceName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem =>school.First(i=>i.Id== item.schoolId).schoolName)
                        </td>
                        <td>
                            @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Detaylar", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Sil", "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }

            </table>
        </div>
        <!-- /.box-body -->
        <a href="@Url.Action("Create","Services")" class="btn btn-primary">Yeni Kayıt Oluştur</a>
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->