StudentTracking.WebHost/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudtentTracking.Data.Entities;
using StudentTracking.Data.Contracts.Repository;
using Microsoft.AspNet.Identity;
using StudentTracking.WebHost.Helper;

namespace StudentTracking.WebHost.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        private readonly IStudentRepository _studentRepository;
        private readonly ISchoolRepository _schoolRepository;
        private readonly IServiceRepository _serviceRepository;

        private readonly string userId = UserInfoHelper.GetUserId();
        public StudentsController(IStudentRepository studentRepository, ISchoolRepository schoolRepository, IServiceRepository serviceRepository)
        {
            _studentRepository = studentRepository;
            _schoolRepository = schoolRepository;
            _serviceRepository = serviceRepository;
        }

        // GET: Students
        public ActionResult Index()
        {
            ViewBag.Schools = _schoolRepository.GetAll();
            ViewBag.Services = _serviceRepository.GetAll();
            return View(_studentRepository.GetAllByUserId(userId).ToList());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = _studentRepository.Get(id);
            if (student == null)
            {
                return HttpNotFound();
            }

            if (student.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.School = _schoolRepository.Get(student.schoolId);
            ViewBag.Service = _serviceRepository.Get(student.serviceId);
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            ViewBag.SchoolsSelectList = SelectListItemHelper.SchoolsKeyValues();
            ViewBag.ServicesSelectList = SelectListItemHelper.ServicesKeyValues();
            ViewBag.GenderSelectList = SelectListItemHelper.GenderKeyValues();
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "studentName,studentId,schoolId,serviceId,identityNumber,parentName,checkIn,checkOut,gender")] Student student)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    student.createdAt = DateTime.Now;
                    student.deletedAt = new DateTime(1800, 1, 1);
                    student.userId = HttpContext.User.Identity.GetUserId();
                    _studentRepository.Insert(student);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = "Kayıt Ekleme İşlemi Başarısız. " + ex.Message;
                    return RedirectToAction("Error","Shared");
                }

            }

            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Student student = _studentRepository.Get(id);
            if (student == null)
            {
                return HttpNotFound();
            }

            if (student.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            var schools = SelectListItemHelper.SchoolsKeyValues();
            schools.Where(i => i.Value == student.schoolId.ToString()).First(j => j.Selected = true);

            var services = SelectListItemHelper.ServicesKeyValues();
            services.Where(i => i.Value == student.serviceId.ToString()).First(j => j.Selected = true);

            var genders = SelectListItemHelper.GenderKeyValues();
            if (student.gender != null)
                genders.First(f => f.Value == student.gender).Selected = true;
            else
                student.gender = "";

            ViewBag.Schools = schools;
            ViewBag.Services = services;
            ViewBag.Genders = genders;
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,studentName,studentId,schoolId,serviceId,identityNumber,parentName,checkIn,checkOut,gender,createdAt,deletedAt,deleted")] Student student)
        {
            if (!ModelState.IsValid)
            {
                return View(student);
            }

            try
            {
                var studentTemp = _studentRepository.Get(student.Id);

                if (studentTemp.userId != UserInfoHelper.GetUserId())
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                student.userId = UserInfoHelper.GetUserId();
                _studentRepository.Update(student);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Düzenleme İşlemi Başarısız. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }

        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = _studentRepository.Get(id);
            if (student == null)
            {
                return HttpNotFound();
            }

            if (student.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.school = _schoolRepository.Get(student.schoolId);
            ViewBag.service = _serviceRepository.Get(student.serviceId);
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Student student = _studentRepository.Get(id);

                if (student.userId != UserInfoHelper.GetUserId())
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                _studentRepository.Delete(student);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Silme İşlemi Başarısız. " + ex.Message;
                return RedirectToAction("Error","Shared");
            }

        }

      

    }
}

StudentTracking.WebHost/Views/Students/Create.cshtml
@model StudtentTracking.Data.Entities.Student
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Öğrenci Oluştur</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="form-horizontal col-md-6 col-sm-12">

                @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.studentName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.studentName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.studentName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.studentId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.studentId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.studentId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.schoolId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.schoolId, new SelectList(ViewBag.SchoolsSelectList, "Value", "Text"), "Okul Seçiniz",  new { @class = "form-control"  })

                        @*@Html.ValidationMessageFor(model => model.schoolId, "", new { @class = "text-danger" })*@
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.serviceId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.serviceId, new SelectList(ViewBag.ServicesSelectList, "Value", "Text"), "Servis Seçiniz", new { @class = "form-control" })
                        @*@Html.ValidationMessageFor(model => model.serviceId, "", new { @class = "text-danger" })*@
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.identityNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.identityNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.identityNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.parentName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.parentName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.parentName, "", new { @class = "text-danger" })
                    </div>
                </div>
              
                <div class="form-group">
                    @Html.LabelFor(model=>model.gender, htmlAttributes:new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.gender, new SelectList(ViewBag.GenderSelectList, "Value", "Text"), "Seçiniz", new { @class = "form-control" })
                        @*@Html.ValidationMessageFor(model => model.gender, "", new { @class="text-danger"})*@
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-6">
                        <input type="submit" value="Oluştur" class="btn btn-success" />
                        <a href="@Url.Action("Index","Students")" class="btn btn-default">Öğrenci Listesine Geri Dön</a>
                    </div>
                </div>

                }



            </div>
        </div>

    </div>
</section>
@section Styles{


}

@section Scripts{

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

StudentTracking.WebHost/Views/Students/Delete.cshtml
@model StudtentTracking.Data.Entities.Student

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var service = (StudtentTracking.Data.Entities.Service)ViewBag.service;
    var school = (StudtentTracking.Data.Entities.School)ViewBag.school;
}

<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
      
        <div class="box-body table-responsive">

           
            <h3>Silmek İstediğine Emin Misin?</h3>
            <div>
              
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.studentName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.studentName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.studentId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.studentId)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.schoolId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => school.schoolName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.serviceId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => service.serviceName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.identityNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.identityNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.parentName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.parentName)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Sil" class="btn btn-default" /> |
                       <a href="@Url.Action("Index","Students")" class="btn btn-primary">Listeye Geri Dön</a>
                    </div>
                }
            </div>

        </div>
        <!-- /.box-body -->     
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

StudentTracking.WebHost/Views/Students/Details.cshtml
@model StudtentTracking.Data.Entities.Student

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var school = (StudtentTracking.Data.Entities.School)ViewBag.School;
    var service = (StudtentTracking.Data.Entities.Service)ViewBag.Service;
}


<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Öğrenci Detayı</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
             
            </div>
        </div>
        <div class="box-body">
            <div>

                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.studentName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.studentName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.studentId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.studentId)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.schoolId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => school.schoolName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.serviceId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => service.serviceName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.identityNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.identityNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.parentName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.parentName)
                    </dd>
              
                </dl>
            </div>

            <div class="col-md-offset-1 col-md-6">
                <a href="@Url.Action("Edit","Students", new { id = Model.Id })" class="btn btn-primary">Düzenle</a>
                <a href="@Url.Action("Index","Students")" class="btn btn-primary">Listeye Geri Dön</a>

            </div>

        </div>
    </div>
    </section>

StudentTracking.WebHost/Views/Students/Edit.cshtml
@model StudtentTracking.Data.Entities.Student
@using StudentTracking.WebHost.Helper
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Düzenle</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="box-body">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal col-md-6">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.studentName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.studentName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.studentName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.gender, new SelectList(ViewBag.Genders, "Value", "Text", Model.gender), "Seçiniz",new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.studentId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.studentId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.studentId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.schoolId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.schoolId, new SelectList(ViewBag.Schools, "Value", "Text", Model.schoolId), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.schoolId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.serviceId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.serviceId, new SelectList(ViewBag.Services, "Value", "Text", Model.serviceId), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.serviceId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.identityNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.identityNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.identityNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.parentName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.parentName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.parentName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @Html.HiddenFor(model => model.createdAt, new { @Value = Model.createdAt.ToString("yyyy-MM-dd") })
                    @Html.HiddenFor(model => model.deletedAt, new { @Value = Model.deletedAt.ToString("yyyy-MM-dd") })
                    @Html.HiddenFor(model=>model.deleted, new { @Value=Model.deleted})
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Kaydet" class="btn btn-default" />
                        <a href="@Url.Action("Index","Students")" class="btn btn-primary">Listeye Dön</a>
                    </div>
                </div>
            </div>
            }

        </div>
        <!-- /.box-body -->

    </div>
    <!-- /.box -->
</section>
<!-- /.content -->


@section Scripts{

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

StudentTracking.WebHost/Views/Students/Index.cshtml
@model IEnumerable<StudtentTracking.Data.Entities.Student>
@using StudtentTracking.Data.Entities
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var schoolObj = (IEnumerable<School>)ViewBag.Schools;
    var serviceObj = (IEnumerable<Service>)ViewBag.Services;
}

<style>
    .btn {
        margin: 10px 10px 10px 10px;
    }
</style>
<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Öğrenciler</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body table-responsive">

            <table class="table table-condensed">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.studentName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.studentId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.schoolId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.serviceId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.identityNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.parentName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.gender)
                    </th>
                    <th>İşlem</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.studentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.studentId)
                        </td>                    
                     
                        <td>
                            @Html.DisplayFor(model=> schoolObj.First(i=>i.Id==item.schoolId).schoolName)
                        </td>
                        <td>
                            @Html.DisplayFor(Model=>serviceObj.First(f=>f.Id==item.serviceId).serviceName)
                        </td>
                          
                        <td>
                            @Html.DisplayFor(modelItem => item.identityNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.parentName)
                        </td>
                       <td>
                           @Html.DisplayFor(modelItem=>item.gender)
                       </td>
                        <td>
                            @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Detaylar", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Sil", "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }

            </table>
        </div>
        <!-- /.box-body -->
        <a href="@Url.Action("Create","Students")" class="btn btn-primary">Yeni Öğrenci Oluştur</a>
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->