StudentTracking.WebHost/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudtentTracking.Data.Entities;
using StudentTracking.Data.Contracts.Repository;
using Microsoft.AspNet.Identity;
using StudentTracking.WebHost.Helper;

namespace StudentTracking.WebHost.Controllers
{
    [Authorize]
    public class LocationsController : Controller
    {
        private readonly ILocationRepository _locationRepository;
        private readonly IStudentRepository _studentRepository;
        public LocationsController(ILocationRepository locationRepository, IStudentRepository studentRepository)
        {
            _locationRepository = locationRepository;
            _studentRepository = studentRepository;
        }
        // GET: Locations
        public ActionResult Index()
        {
            ViewBag.students = _studentRepository.GetAll();
            return View(_locationRepository.GetAllByUserId(UserInfoHelper.GetUserId()).ToList());
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = _locationRepository.Get(id);
            if (location == null)
            {
                return HttpNotFound();
            }

            if (location.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(location);
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            ViewBag.students = Helper.SelectListItemHelper.StudentsKeyValues();
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "studentId,locationName,latitude,longitude,createdAt,deletedAt,deleted")] Location location)
        {
            if (!ModelState.IsValid)
                return View(location);

            try
            {
                location.userId = HttpContext.User.Identity.GetUserId();
                location.deleted = false;
                location.deletedAt = new DateTime(1900, 1, 1);
                location.createdAt = DateTime.Now;
                _locationRepository.Insert(location);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Kayıt Eklenemedi. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }
                return RedirectToAction("Index");

        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = _locationRepository.Get(id);
            if (location == null)
            {
                return HttpNotFound();
            }

            if (location.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,studentId,locationName,latitude,longitude,createdAt,deletedAt,deleted")] Location location)
        {
            if (!ModelState.IsValid)
                return View(location);

            try
            {
                var locationTemp = _locationRepository.Get(location.Id);

                if (locationTemp.userId != UserInfoHelper.GetUserId())
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                _locationRepository.Update(location);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Düzenleme İşlemi Başarısız. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }

            return RedirectToAction("Index");
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = _locationRepository.Get(id);
            if (location == null)
            {
                return HttpNotFound();
            }

            if (location.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Location location = _locationRepository.Get(id);

                if (location.userId != UserInfoHelper.GetUserId())
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                _locationRepository.Delete(location);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Silme İşlemi Başarısız. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }

            return RedirectToAction("Index");
        }

    }
}

StudentTracking.WebHost/Views/Locations/Create.cshtml
@model StudtentTracking.Data.Entities.Location

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Yeni Kayıt Oluştur</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="box-body">
            <div class="form-horizontal col-md-6 col-sm-12">

                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.studentId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.studentId, new SelectList(ViewBag.students,"Value", "Text"),"Seçiniz", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.studentId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.locationName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.locationName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.locationName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
                        </div>
                    </div>
                
                    <div class="form-group">
                        <div class="col-md-offset-4 col-md-6">
                            <input type="submit" value="Oluştur" class="btn btn-success" />
                            <a href="@Url.Action("Index","Locations")" class="btn btn-default">Listeye Geri Dön</a>
                        </div>
                    </div>

                }



            </div>
        </div>

    </div>
</section>


@section Styles{



}

@section Scripts{

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

StudentTracking.WebHost/Views/Locations/Delete.cshtml
@model StudtentTracking.Data.Entities.Location

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">

        <div class="box-body table-responsive">


            <h3>Silmek İstediğine Emin Misin?</h3>
            <div>

                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.studentId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.studentId)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.locationName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.locationName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.latitude)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.latitude)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.longitude)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.longitude)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.createdAt)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.createdAt)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.deletedAt)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.deletedAt)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.deleted)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.deleted)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Sil" class="btn btn-default" /> |
                        <a href="@Url.Action("Index","Locations")" class="btn btn-primary">Listeye Geri Dön</a>
                    </div>
                }
            </div>

        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

StudentTracking.WebHost/Views/Locations/Details.cshtml
@model StudtentTracking.Data.Entities.Location

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Lokasyon Detayı</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="box-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.studentId)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.studentId)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.locationName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.locationName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.latitude)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.latitude)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.longitude)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.longitude)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.createdAt)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.createdAt)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.deletedAt)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.deletedAt)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.deleted)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.deleted)
                </dd>

            </dl>
            <div class="col-md-offset-1 col-md-6">
                <a href="@Url.Action("Edit","Locations", new { id = Model.Id })" class="btn btn-primary">Düzenle</a>
                <a href="@Url.Action("Index","Locations")" class="btn btn-primary">Listeye Geri Dön</a>

            </div>

        </div>
    </div>
</section>

StudentTracking.WebHost/Views/Locations/Edit.cshtml
@model StudtentTracking.Data.Entities.Location

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Düzenle</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="box-body">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)


                    <div class="form-group">
                        @Html.LabelFor(model => model.studentId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.studentId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.studentId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.locationName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.locationName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.locationName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.createdAt, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.createdAt, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.createdAt, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.deletedAt, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.deletedAt, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.deletedAt, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.deleted, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.deleted)
                                @Html.ValidationMessageFor(model => model.deleted, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Kaydet" class="btn btn-default" />
                            <a href="@Url.Action("Index","Locations")" class="btn btn-primary">Listeye Dön</a>
                        </div>
                    </div>
                </div>
            }

        </div>
        <!-- /.box-body -->

    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

@section Scripts{

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

StudentTracking.WebHost/Views/Locations/Index.cshtml
@model IEnumerable<StudtentTracking.Data.Entities.Location>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var students = (IEnumerable<StudtentTracking.Data.Entities.Student>)ViewBag.students;
}

<!-- Content Header (Page header) -->
<section class="content-header"></section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Lokasyonlar</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>

            </div>
        </div>
        <div class="box-body table-responsive">

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.studentId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.locationName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.latitude)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.longitude)
                    </th>
                    <th>İşlem</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => students.First(f=>f.Id==item.studentId).studentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.locationName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.latitude)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.longitude)
                        </td>
                        <td>
                            @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Detaylar", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Sil", "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }

            </table>

        </div>
        <!-- /.box-body -->
        <a href="@Url.Action("Create","Locations")" class="btn btn-primary">Yeni Kayıt Oluştur</a>
    </div>
    <!-- /.box -->
</section>
<!-- /.content -->