StudentTracking.WebHost/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudtentTracking.Data.Entities;
using StudentTracking.Data.Contracts.Repository;
using Microsoft.AspNet.Identity;
using StudentTracking.WebHost.Helper;

namespace StudentTracking.WebHost.Controllers
{
    [Authorize]
    public class ContactsController : Controller
    {
        private readonly IContactRepository _contactRepository;
        private readonly IStudentRepository _studentRepository;               
        public ContactsController(IContactRepository contactRepository, IStudentRepository studentRepository)
        {
            _contactRepository = contactRepository;
            _studentRepository = studentRepository;
        }

        // GET: ContactInformations
        public ActionResult Index()
        {
            ViewBag.Students = _studentRepository.GetAllByUserId(UserInfoHelper.GetUserId());
            return View(_contactRepository.GetAllByUserId(UserInfoHelper.GetUserId()).ToList());
        }

        // GET: ContactInformations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactInformation contactInformation = _contactRepository.Get(id);
            if (contactInformation == null)
            {
                return HttpNotFound();
            }

            if (contactInformation.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.studentName = _studentRepository.Get(contactInformation.studentId).studentName;
            return View(contactInformation);
        }

        // GET: ContactInformations/Create
        public ActionResult Create()
        {
            ViewBag.StudentSelectList = SelectListItemHelper.StudentsKeyValues();
            return View();
        }

        // POST: ContactInformations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "studentId,phoneNumber,createdAt,deletedAt,deleted")] ContactInformation contactInformation)
        {
            if (!ModelState.IsValid)
            {
                 return View(contactInformation);
            }

            try
            {
                contactInformation.createdAt = DateTime.Now;
                contactInformation.deletedAt = new DateTime(1900, 1, 1);
                contactInformation.userId = HttpContext.User.Identity.GetUserId();
                _contactRepository.Insert(contactInformation);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Kayıt Ekleme İşlemi Başarısız. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }
                return RedirectToAction("Index");

        }

        // GET: ContactInformations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactInformation contactInformation = _contactRepository.Get(id);
            if (contactInformation == null)
            {
                return HttpNotFound();
            }

            if (contactInformation.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.StudentName = _studentRepository.Get(contactInformation.studentId).studentName;
            return View(contactInformation);
        }

        // POST: ContactInformations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,studentId,phoneNumber,createdAt,deletedAt,deleted")] ContactInformation contactInformation)
        {
            if (ModelState.IsValid)
            {
                var contactTemp = _contactRepository.Get(contactInformation.Id);
                if (contactTemp.userId != UserInfoHelper.GetUserId())
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                _contactRepository.Update(contactInformation);
                return RedirectToAction("Index");
            }
            return View(contactInformation);
        }

        // GET: ContactInformations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactInformation contactInformation = _contactRepository.Get(id);
            if (contactInformation == null)
            {
                return HttpNotFound();
            }

            if (contactInformation.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.StudentName = _studentRepository.Get(contactInformation.studentId).studentName;
            return View(contactInformation);
        }

        // POST: ContactInformations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                ContactInformation contactInformation = _contactRepository.Get(id);

                if (contactInformation.userId != UserInfoHelper.GetUserId())
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                _contactRepository.Delete(contactInformation);
            }
            catch (Exception ex)
            {
                throw new Exception("Silme işlemi başarısız! "+ ex.Message);
            }
          
            return RedirectToAction("Index");
        }

    }
}

StudentTracking.WebHost/Controllers/SchoolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudtentTracking.Data.Entities;
using StudentTracking.Data.Contracts.Repository;
using Microsoft.AspNet.Identity;
using StudentTracking.WebHost.Helper;

namespace StudentTracking.WebHost.Controllers
{
    [Authorize]
    public class SchoolsController : Controller
    {

        private readonly ISchoolRepository _schoolRepository;
        public SchoolsController(ISchoolRepository schoolRepository)
        {
            _schoolRepository = schoolRepository;
        }
        // GET: Schools
        public ActionResult Index()
        {
            return View(_schoolRepository.GetAllByUserId(UserInfoHelper.GetUserId()).ToList());
        }

        // GET: Schools/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = _schoolRepository.Get(id);

            if (school == null)
            {
                return HttpNotFound();
            }

            if (school.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(school);
        }

        // GET: Schools/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Schools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "schoolName,createdAt,deletedAt,deleted")] School school)
        {
            if (ModelState.IsValid)
            {
                school.deleted = false;
                school.deletedAt = new DateTime(1900, 1, 1);
                school.createdAt = DateTime.Now;
                school.userId = HttpContext.User.Identity.GetUserId();
                _schoolRepository.Insert(school);
                return RedirectToAction("Index");
            }

            return View(school);
        }

        // GET: Schools/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = _schoolRepository.Get(id);
            if (school == null)
            {
                return HttpNotFound();
            }

            if (school.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(school);
        }

        // POST: Schools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,schoolName,createdAt,deletedAt,deleted")] School school)
        {
            if (!ModelState.IsValid)
            {
                return View(school);
            }

            var schoolTemp = _schoolRepository.Get(school.Id);
            if (schoolTemp.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            try
            {
                _schoolRepository.Update(school);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Düzenleme işlemi başarısız. " + ex.Message;
                return RedirectToAction("Error", "Shared");
            }
            return RedirectToAction("Index");

        }

        // GET: Schools/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = _schoolRepository.Get(id);
            if (school == null)
            {
                return HttpNotFound();
            }

            if (school.userId != UserInfoHelper.GetUserId())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(school);
        }

        // POST: Schools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                School school = _schoolRepository.Get(id);

                if (school.userId != UserInfoHelper.GetUserId())
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

                _schoolRepository.Delete(school);
            }
            catch (Exception ex)
            {
                throw new Exception("Silme işlemi başarısız! " + ex.Message);

            }
            return RedirectToAction("Index");

        }

    }
}

StudentTracking.WebHost/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudtentTracking.Data.Entities;
using StudentTracking.Data.Contracts.Repository;

namespace StudentTracking.WebHost.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly IUsersRepository _userRepository;
        public UsersController(IUsersRepository userRepository)
        {
            _userRepository = userRepository;
        }

        // GET: Users
        public ActionResult Index()
        {
            return View(_userRepository.GetAll().ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User users = _userRepository.Get(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userId,username,password,email,role,createdAt,deletedAt,deleted")] User users)
        {
            if (ModelState.IsValid)
            {
                users.userId = Helper.UserInfoHelper.GetUserId();
                users.deleted = false;
                users.deletedAt = new DateTime(1900, 1, 1);
                users.createdAt = DateTime.Now;
                _userRepository.Insert(users);
                return RedirectToAction("Index");
            }

            return View(users);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User users = _userRepository.Get(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,userId,username,password,email,role,createdAt,deletedAt,deleted")] User users)
        {
            if (ModelState.IsValid)
            {
              _userRepository.Update(users);
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User users = _userRepository.Get(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User users = _userRepository.Get(id);
            _userRepository.Delete(users);
            return RedirectToAction("Index");
        }
        
    }
}

StudentTracking.WebHost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Content/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Content/dist/css/skins/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @RenderSection("Styles", false)
    <style>
        .btn{
            margin:10px 10px 10px 10px;
        }
    </style>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index","Home")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>S</b>T</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Student</b>Track</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

            </nav>
        </header>
        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">

                    <li class="header">LABELS</li>
                    <li><a href="@Url.Action("Index","Students")"><i class="fa fa-circle-o text-red"></i> <span>Öğrenciler</span></a></li>
                    <li><a href="@Url.Action("Index","Schools")"><i class="fa fa-circle-o text-yellow"></i> <span>Okullar</span></a></li>
                    <li><a href="@Url.Action("Index","Services")"><i class="fa fa-circle-o text-aqua"></i> <span>Servisler</span></a></li>
                    <li><a href="@Url.Action("Index","Contacts")"><i class="fa fa-circle-o text-aqua"></i> <span>İletişim Bilgileri</span></a></li>
                    <li><a href="@Url.Action("Index","Locations")"><i class="fa fa-circle-o text-aqua"></i> <span>Lokasyonlar</span></a></li>
                    @*<li><a href="@Url.Action("Index","Users")"><i class="fa fa-circle-o text-aqua"></i> <span>Kullanıcılar</span></a></li>*@

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()

        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 1.0
            </div>
            <strong>Copyright &copy; 2017 <a href="#">CreaWorks</a>.</strong> All rights
            reserved.
        </footer>

    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Content/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/Content/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.min.js"></script>
    <script src="~/Content/dist/js/app.min.js"></script>
    @RenderSection("Scripts", false)
    <script>
  $(document).ready(function () {
    $('.sidebar-menu').tree()
  })
    </script>
    
  
</body>
</html>